---
kind: pipeline
name: default

# Test PR

steps:
  - name: build
    image: thegeeklab/drone-docker-buildx:20.12.1@sha256:5439d579562a605953b386df64f1a469720f5358fa1bd0bdf225ae8d48d652b7
    settings:
      auto_tag: true
      repo: mazzolino/drone-test
      cache_from: mazzolino/drone-test:cache
      cache_to: mazzolino/drone-test:cache
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/armhf
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    exclude:
      - pull_request

---
kind: pipeline
name: build pr

steps:
  - name: build pr
    image: thegeeklab/drone-docker-buildx:20.12.1@sha256:5439d579562a605953b386df64f1a469720f5358fa1bd0bdf225ae8d48d652b7
    settings:
      repo: mazzolino/drone-test
      tags:
        - pr-${DRONE_PULL_REQUEST}
      cache_from: mazzolino/drone-test:cache
      cache_to: mazzolino/drone-test:cache
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/armhf
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - pull_request
---
kind: signature
hmac: 0b9387e6d04857af29b1a0c0ea9dc84c488305f9334cd4becd0b1cdcc019bbc7

...
