---
kind: pipeline
name: default

# Test PR

steps:
  - name: build
    image: thegeeklab/drone-docker-buildx:20.12@sha256:f17c2e4008ad8cee699b26d97d52974bf6e78e700ed654e589191a5afac56e81
    settings:
      auto_tag: true
      repo: mazzolino/drone-test
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/armhf
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    exclude:
      - pull_request

---
kind: pipeline
name: build pr

steps:
  - name: build pr
    image: thegeeklab/drone-docker-buildx:20.12@sha256:f17c2e4008ad8cee699b26d97d52974bf6e78e700ed654e589191a5afac56e81
    settings:
      repo: mazzolino/drone-test
      tags:
        - pr-${DRONE_PULL_REQUEST}
      dry_run: true
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/armhf
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - pull_request
